name: word_of_the_day
description: Dictionary.com&#x27;s Word of the Day
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^2.0.1
  html: ^0.14.0+2
  http: ^0.12.0+2
  webview_flutter: ^0.3.7+1
  url_launcher: ^5.0.2
  fluttery_audio: ^0.0.4
  fluttertoast: ^3.1.0
  connectivity: ^0.4.3+1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
